// <auto-generated />
using EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A fictional story about a magical School.",
                            IsActive = true,
                            NoOfPages = 300,
                            Title = "Harry potter"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Character development",
                            IsActive = true,
                            NoOfPages = 200,
                            Title = "Ego is Enemy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Character development",
                            IsActive = true,
                            NoOfPages = 340,
                            Title = "Obstacle is the way"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Character development",
                            IsActive = true,
                            NoOfPages = 342,
                            Title = "Raaz e Hayat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
